//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mfmWeighment {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class APPSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static APPSetting defaultInstance = ((APPSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new APPSetting())));
        
        public static APPSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cfgSQLServer {
            get {
                return ((string)(this["cfgSQLServer"]));
            }
            set {
                this["cfgSQLServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cfgSQLUser {
            get {
                return ((string)(this["cfgSQLUser"]));
            }
            set {
                this["cfgSQLUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cfgSQLPassword {
            get {
                return ((string)(this["cfgSQLPassword"]));
            }
            set {
                this["cfgSQLPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cfgAPPDB {
            get {
                return ((string)(this["cfgAPPDB"]));
            }
            set {
                this["cfgAPPDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cfgSBODB {
            get {
                return ((string)(this["cfgSBODB"]));
            }
            set {
                this["cfgSBODB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cfgSapID {
            get {
                return ((string)(this["cfgSapID"]));
            }
            set {
                this["cfgSapID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cfgSapPw {
            get {
                return ((string)(this["cfgSapPw"]));
            }
            set {
                this["cfgSapPw"] = value;
            }
        }
    }
}
